name: Build + tests

on:  
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    name: Build and Install Package, Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel pytest pytest-asyncio
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .
      - name: Run Tests
        run: |
          python -m pytest tests/ --tb=short --disable-warnings