name: Build + tests

on:  
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    name: Build and Install Package, Run Tests - ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: ubuntu
            runs-on: ubuntu-latest
          - os: windows
            runs-on: windows-latest
          - os: freebsd
            runs-on:
              - self-hosted
              - freebsd
    env:
      TEST_V2RAY_LINK: ${{ secrets.TEST_V2RAY_LINK }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel pytest pytest-asyncio
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Build the Package
        run: |
          python -m pip install -e .
      - name: Run Tests
        run: |
          python -m pytest tests/ --tb=short --disable-warnings